// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhfoKB7-WobwlV7I_Vp96AXavxY8-xlfw',
    appId: '1:1080872204170:android:d63555e40e218bb5d07a73',
    messagingSenderId: '1080872204170',
    projectId: 'flutter-fyp-14b4c',
    storageBucket: 'flutter-fyp-14b4c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZEw9xvqfnMQFjEvA2qeM8GNMK8MwxaHY',
    appId: '1:1080872204170:ios:25b782d4ed0b7467d07a73',
    messagingSenderId: '1080872204170',
    projectId: 'flutter-fyp-14b4c',
    storageBucket: 'flutter-fyp-14b4c.firebasestorage.app',
    iosBundleId: 'com.example.worknest',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ04Y2Sh0HYSorRDpHQAjmnV0t_HgGuD8',
    appId: '1:1080872204170:web:1b7cc9432af52063d07a73',
    messagingSenderId: '1080872204170',
    projectId: 'flutter-fyp-14b4c',
    authDomain: 'flutter-fyp-14b4c.firebaseapp.com',
    storageBucket: 'flutter-fyp-14b4c.firebasestorage.app',
    measurementId: 'G-8VMNC8EVWE',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZEw9xvqfnMQFjEvA2qeM8GNMK8MwxaHY',
    appId: '1:1080872204170:ios:25b782d4ed0b7467d07a73',
    messagingSenderId: '1080872204170',
    projectId: 'flutter-fyp-14b4c',
    storageBucket: 'flutter-fyp-14b4c.firebasestorage.app',
    iosBundleId: 'com.example.worknest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBo-QViqF_6xaDFhXkJodEK3sj2kiuYPzY',
    appId: '1:1080872204170:web:9a002cbb005cc933d07a73',
    messagingSenderId: '1080872204170',
    projectId: 'flutter-fyp-14b4c',
    authDomain: 'flutter-fyp-14b4c.firebaseapp.com',
    storageBucket: 'flutter-fyp-14b4c.firebasestorage.app',
    measurementId: 'G-3JWJ5057BL',
  );

}